[package]
name = "helloworld"
version = "0.1.0"
authors = ["Jay Two"]
edition = "2019"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

